
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3064"
  end

  # Configure provisioners on tha machine
  config.vm.provision :docker
  config.vm.provision :docker_compose

  # Server 1
  config.vm.define "ci-server" do |ciserver|
    ciserver.vm.network "private_network", ip: '192.168.56.60'
    ciserver.vm.hostname = "ci-server"
    ciserver.vm.provision :file, source: "../docker/docker-compose.ci.yml", destination: "docker-compose.yml"
    ciserver.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
    ciserver.vm.provision :shell, inline: "sudo chmod 777 /var/run/docker.sock"
  end
end
