
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "5064"
  end

  # Configure provisioners on tha machine
  config.vm.provision :docker
  config.vm.provision :shell, inline: "sudo chmod 777 /var/run/docker.sock"

  # Server 1
  config.vm.define "server1" do |server1|
    server1.vm.network "private_network", ip: '192.168.56.60'
    server1.vm.hostname = "ci-server"
    server1.vm.provision :docker_compose
    server1.vm.provision :file, source: "../docker/docker-compose.ci.yml", destination: "docker-compose.yml"
    server1.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
  end

  # Server 2
  config.vm.define "server2" do |server2|
    server2.vm.network "private_network", ip: '192.168.56.61'
    server2.vm.hostname = "server2"
  end

  # Server 3
  config.vm.define "server3" do |server3|
    server3.vm.network "private_network", ip: '192.168.56.62'
    server3.vm.hostname = "server3"
    server3.vm.provision :docker_compose
    server3.vm.provision :file, source: "../docker/docker-compose.cd.yml", destination: "docker-compose.yml"
    server3.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
  end
end
